params:
  firstName: Coline
  lastName: Metta-Versmessen

  description: PhD, Climate Economics Chair (CEC, Paris) and Lille Economie Management (LEM, Lille)

  email: "c.mettaversmessen@gmail.com"
  linkedin: "https://www.linkedin.com/in/coline-metta-versmessen/"
  orcid: "https://orcid.org/0009-0003-5405-8021"

menus:
  main:
    - name: Scientific Production
      url: /papers/
      weight: 1
    - name: Scientific Events
      url: /events/
      weight: 2
    - name: Teaching
      url: /teaching/
      weight: 3
    - name: Curriculum Vitae
      url: /cv.pdf
      weight: 4

# allows to render `<br/>` on the Teaching page
markup:
  goldmark:
    renderer:
      unsafe: true
